# Generated by Django 4.2.3 on 2023-07-31 00:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tarefa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tarefa", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pd", "pendente"),
                            ("ea", "em andamento"),
                            ("cc", "concluida"),
                            ("cl", "cancelada"),
                        ],
                        max_length=15,
                    ),
                ),
                ("data_criacao", models.DateTimeField(default=datetime.datetime.now)),
                ("data_prazo", models.DateTimeField(default=datetime.datetime.now)),
                ("data_conclusao", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
