# Generated by Django 4.2.3 on 2023-07-31 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_alter_tarefa_data_conclusao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tarefa",
            name="data_conclusao",
            field=models.DateField(null=True),
        ),
    ]
