# Generated by Django 4.2.3 on 2023-07-31 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_alter_tarefa_data_conclusao"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tarefa",
            name="data_conclusao",
        ),
        migrations.RemoveField(
            model_name="tarefa",
            name="data_prazo",
        ),
    ]
