# Generated by Django 4.2.3 on 2023-08-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_remove_tarefa_data_conclusao_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tarefa",
            name="status",
            field=models.CharField(
                choices=[
                    ("pd", "pendente"),
                    ("ea", "em andamento"),
                    ("cc", "concluida"),
                ],
                max_length=15,
            ),
        ),
    ]
